networks:
  static-ip:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16

services:
  postgres:
    networks:
      default: ~
      static-ip:
        ipv4_address: 10.6.0.4

  redis:
    networks:
      default: ~
      static-ip:
        ipv4_address: 10.6.0.5

  n8n:
    environment:
      - N8N_PROTOCOL=https
      - N8N_HOST=n8n.antennae.space
      - N8N_PORT=443
    networks:
      default: ~
      static-ip:
        ipv4_address: 10.6.0.10